### ISSUE TITLE
Improperly formatted content on one Github page.

### ISSUE THREAD

**Issue by VirenMohindra** [dbkaplun/github-markdown-outline-extension#2]
Attached here you can see that the extension fails when it doesn't have any space to wrap around text.

I can't seem to see the remaining headers without zooming out.

Also it doesn't look as appealing as it should.

<img width="1418" alt="screenshot" src="https://cloud.githubusercontent.com/assets/10460518/11763335/ccd4c668-a0d4-11e5-8921-92f57df22162.png">

**Comment by dbkaplun** [comment]
Hi @VirenMohindra, you should be able to turn off the fixed functionality which will move the outline directly into the markdown document. Please copy and paste this URL into Chrome: `chrome://extensions/?options=gccinjjdbfdkkkebfbeipopijjfohfgj` and disable the checkbox next to "Fix outline to side if there's enough room" then refresh the page.

Does that help?

**Comment by VirenMohindra** [comment]
It seems to be working well now. Is there some way the formatting can also be fixed or is this a problem which is centric to the document only?

<img width="1421" alt="fix" src="https://cloud.githubusercontent.com/assets/10460518/11763446/e726da0c-a0d8-11e5-84bc-8f17e308eaac.png">

**Comment by dbkaplun** [comment]
Indeed, that is an interesting problem. I can't think of a general solution off the top of my head. I'll reopen for now, maybe somebody else can think of an approach.

**Comment by dbkaplun** [comment]
1.1.0 now attempts to detect whether an outline is already present before adding another outline. Feel free to update the issue if you find a page that isn't properly detected.

**Comment by dbkaplun** [comment]
Implemented the `normalize` option as of 1.3.0 which ensures each header isn't indented more than one level at a time.

![screenshot](http://imgur.com/Hk5d49O.png)
