### ISSUE TITLE
Not Rendering

### ISSUE THREAD

**Issue by philwinder** [dbkaplun/github-markdown-outline-extension#3]
Hi @dbkaplun, nice idea you have here.

But when I view any md file, it doesn't seem to render anything. See screenshot of your test file below.

Chrome Version 55.0.2883.95 (64-bit)

![screen shot 2017-01-22 at 10 02 13](https://cloud.githubusercontent.com/assets/8793723/22181742/1a786b2c-e08a-11e6-9deb-b617bbd2fcb3.png)

**Comment by dbkaplun** [comment]
If you would like an outline to appear on all pages:
* `chrome://extensions/?options=ojlinlnjcbcipemmmhddigcmmclfpkle`
* Disable "Hide outline if one is already present"

Hope this helps!

**Comment by philwinder** [comment]
That works! Thanks.

Would be great if this worked on other providers too. Gitlab/bitbucket, etc.
